### ISSUE TITLE
Version 6.0.2 not customizable in Angular 6.0.x

### ISSUE THREAD

**Issue by ChrisRescher** [andreasonny83/angular2-cookie-law#26] opened 2018-06-08 07:37 UTC
Hi,

It is not possible to customize the directive, like this:

`<cookie-law>Hallo Chris Cookie</cookie-law>`

**Effect you can see under your own demo page as well (using Chrome or Firefox)** 
https://stackblitz.com/edit/angular2-cookie-law

Can reproduce it with fresh Angular Cli 6.0.8 project:

brings the same result like demo Page.

package.json in my demo project:

{
  "name": "testcookie",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.0.4",
    "@angular/common": "^6.0.3",
    "@angular/compiler": "^6.0.3",
    "@angular/core": "^6.0.3",
    "@angular/forms": "^6.0.3",
    "@angular/http": "^6.0.3",
    "@angular/platform-browser": "^6.0.3",
    "@angular/platform-browser-dynamic": "^6.0.3",
    "@angular/router": "^6.0.3",
    "angular2-cookie-law": "^6.0.2",
    "core-js": "^2.5.4",
    "rxjs": "^6.0.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^6.0.3",
    "@angular-devkit/build-angular": "~0.6.8",
    "typescript": "~2.7.2",
    "@angular/cli": "~6.0.8",
    "@angular/language-service": "^6.0.3",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1"
  }
}

**Comment by RenzoRoca** [comment] 2018-06-11 09:17
Same problem, the custom templete option does not work. I'm using Angular cli 6.0.8

**Comment by andreasonny83** [comment] 2018-06-12 16:40
Closing this as duplicate of #25

**Closed by andreasonny83** 2018-06-12 16:40 UTC
